FROM balenalib/%%BALENA_MACHINE_NAME%%:bullseye

ENV DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
ENV UDEV=1

RUN install_packages \
  awscli

COPY cloudwatch /root/cloudwatch
RUN chmod +x /root/cloudwatch

CMD ["/root/cloudwatch"]

#CMD ["nginx", "-g", "daemon off;"]
#CMD [ "tail", "-f", "/dev/null" ]
