FROM balenalib/%%BALENA_MACHINE_NAME%%:stretch

ENV DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket

ENV UDEV=1

RUN install_packages \
  nginx

CMD ["nginx", "-g", "daemon off;"]
#CMD [ "tail", "-f", "/dev/null" ]
